// <auto-generated />
using Message_Board.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Message_Board.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Message_Board.Models.Comments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("comment_mgs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("like")
                        .HasColumnType("int");

                    b.Property<int>("msg_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            comment_mgs = "Same to you",
                            like = 1,
                            msg_id = 1,
                            name = "Kuldeep Nikum"
                        });
                });

            modelBuilder.Entity("Message_Board.Models.Users", b =>
                {
                    b.Property<int>("Msg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Msg_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("like")
                        .HasColumnType("int");

                    b.HasKey("Msg_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Msg_id = 1,
                            Msg_content = "Happy Holi...",
                            User_name = "Mohit Yadav",
                            like = 10
                        },
                        new
                        {
                            Msg_id = 2,
                            Msg_content = "Whatever",
                            User_name = "Kuldeep Nikum",
                            like = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
